@extends('layouts.admin')

@section('title', 'Campaign & ROI')
@section('heading', 'Campaign & ROI')
@if($growthEnabled)@section('header_action')<a class="btn btn-outline-primary" href="{{ route('admin.growth.index') }}">Buka analitik funnel</a>@endsection@endif

@section('content')
<div class="admin-note mb-3">Campaign hanya mengukur sumber dan biaya. Pengiriman broadcast tetap dilakukan manual melalui WhatsApp yang Anda gunakan sekarang.</div>
<details class="admin-panel mb-3" @if($errors->any()) open @endif><summary class="admin-panel-head"><h2>Buat campaign terukur</h2><span>Simpan lalu salin tautan UTM</span></summary><form class="p-4 form-grid" method="post" action="{{ route('admin.marketing-campaigns.store') }}">@csrf
    <label class="field"><span>Nama campaign *</span><input class="form-control" name="name" value="{{ old('name') }}" required></label><label class="field"><span>Kode URL</span><input class="form-control" name="slug" value="{{ old('slug') }}" placeholder="Otomatis dari nama"></label><label class="field"><span>Sumber</span><input class="form-control" name="source" value="{{ old('source','whatsapp') }}" required></label><label class="field"><span>Media</span><input class="form-control" name="medium" value="{{ old('medium','broadcast') }}" required></label>
    <label class="field"><span>Tanggal mulai</span><input class="form-control" type="date" name="start_date" value="{{ old('start_date',now()->format('Y-m-d')) }}"></label><label class="field"><span>Tanggal selesai</span><input class="form-control" type="date" name="end_date" value="{{ old('end_date') }}"></label><label class="field"><span>Budget</span><input class="form-control" type="number" min="0" name="budget" value="{{ old('budget',0) }}"></label><label class="field"><span>Biaya aktual</span><input class="form-control" type="number" min="0" name="spend" value="{{ old('spend',0) }}"></label>
    <label class="field"><span>Status</span><select class="form-select" name="status">@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected($key === 'active')>{{ $label }}</option>@endforeach</select></label><label class="field field-wide"><span>Catatan</span><textarea class="form-control" name="notes" rows="2">{{ old('notes') }}</textarea></label><div><button class="btn btn-primary">Simpan campaign</button></div>
</form></details>

<div class="campaign-grid">@forelse($campaigns as $campaign)<article class="admin-panel"><form class="p-3 stack-form" method="post" action="{{ route('admin.marketing-campaigns.update',$campaign) }}">@csrf @method('PUT')
    <div class="d-flex justify-content-between"><span class="status status-{{ $campaign->status === 'active' ? 'paid' : 'draft' }}">{{ $campaign->statusLabel() }}</span><strong>{{ $campaign->inquiries_count }} lead</strong></div><label class="field"><span>Nama</span><input class="form-control" name="name" value="{{ $campaign->name }}" required></label><label class="field"><span>Kode UTM campaign</span><input class="form-control" name="slug" value="{{ $campaign->slug }}" required></label><div class="row g-2"><label class="field col-6"><span>Sumber</span><input class="form-control" name="source" value="{{ $campaign->source }}"></label><label class="field col-6"><span>Media</span><input class="form-control" name="medium" value="{{ $campaign->medium }}"></label></div><div class="row g-2"><label class="field col-6"><span>Mulai</span><input class="form-control" type="date" name="start_date" value="{{ $campaign->start_date?->format('Y-m-d') }}"></label><label class="field col-6"><span>Selesai</span><input class="form-control" type="date" name="end_date" value="{{ $campaign->end_date?->format('Y-m-d') }}"></label></div><div class="row g-2"><label class="field col-6"><span>Budget</span><input class="form-control" type="number" min="0" name="budget" value="{{ $campaign->budget }}"></label><label class="field col-6"><span>Biaya aktual</span><input class="form-control" type="number" min="0" name="spend" value="{{ $campaign->spend }}"></label></div><label class="field"><span>Status</span><select class="form-select" name="status">@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected($campaign->status === $key)>{{ $label }}</option>@endforeach</select></label><label class="field"><span>Catatan</span><textarea class="form-control" name="notes" rows="2">{{ $campaign->notes }}</textarea></label><button class="btn btn-primary">Simpan perubahan</button>
    <div class="campaign-link-builder"><select class="form-select form-select-sm campaign-target">@foreach($services as $service)<option value="{{ route('services.show',$service->slug) }}">{{ $service->name }}</option>@endforeach<option value="{{ route('proposal.create') }}">Proposal umum</option></select><input class="form-control form-control-sm campaign-link" data-source="{{ $campaign->source }}" data-medium="{{ $campaign->medium }}" data-campaign="{{ $campaign->slug }}" readonly><button class="btn btn-sm btn-outline-primary copy-campaign-link" type="button">Salin tautan</button></div>
</form></article>@empty<div class="empty-state"><h2>Belum ada campaign</h2><p>Buat campaign pertama untuk mulai mengukur biaya per lead dan pembayaran.</p></div>@endforelse</div>
@if($campaigns->hasPages())<div class="mt-3">{{ $campaigns->links() }}</div>@endif
@endsection

@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.campaign-link-builder').forEach(box=>{const target=box.querySelector('.campaign-target'),output=box.querySelector('.campaign-link');const build=()=>{const url=new URL(target.value);url.searchParams.set('utm_source',output.dataset.source);url.searchParams.set('utm_medium',output.dataset.medium);url.searchParams.set('utm_campaign',output.dataset.campaign);output.value=url.toString()};target.addEventListener('change',build);box.querySelector('.copy-campaign-link').addEventListener('click',()=>navigator.clipboard.writeText(output.value));build()})});</script>@endpush
