@extends('layouts.admin')

@section('title', 'Analitik Pertumbuhan')
@section('heading', 'Analitik Pertumbuhan')
@section('header_action')<div class="btn-group">@foreach([7,30,90] as $period)<a class="btn {{ $days === $period ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ route('admin.growth.index', ['days'=>$period]) }}">{{ $period }} hari</a>@endforeach</div>@endsection

@section('content')
<div class="admin-note mb-3">Ringkasan {{ $from->translatedFormat('d F Y') }}–{{ now()->translatedFormat('d F Y') }}. Atribusi mengikuti UTM terakhir yang dibawa pengunjung saat mengirim proposal.</div>
<section class="growth-metrics mb-3">
    <article><span>Lead masuk</span><strong>{{ number_format($metrics['leads']) }}</strong></article><article><span>Penawaran terkirim</span><strong>{{ number_format($metrics['quotes']) }}</strong></article><article><span>Disetujui</span><strong>{{ number_format($metrics['approved_quotes']) }}</strong><small>{{ $metrics['conversion'] }}% dari lead</small></article><article><span>Nilai invoice</span><strong>Rp{{ number_format($metrics['invoiced'], 0, ',', '.') }}</strong></article><article><span>Pembayaran masuk</span><strong>Rp{{ number_format($metrics['collected'], 0, ',', '.') }}</strong></article>
</section>
<div class="row g-3">
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Sumber lead</h2><span>UTM/referral/website</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Sumber</th><th>Lead</th><th>Terkualifikasi</th><th>Potensi</th></tr></thead><tbody>@forelse($sourceRows as $row)<tr><td><strong>{{ $row['name'] }}</strong></td><td>{{ $row['leads'] }}</td><td>{{ $row['qualified'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="4">Belum ada data.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Campaign</h2><span>utm_campaign</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Campaign</th><th>Lead</th><th>Terkualifikasi</th><th>Rasio</th></tr></thead><tbody>@forelse($campaignRows as $row)<tr><td><strong>{{ $row['name'] }}</strong></td><td>{{ $row['leads'] }}</td><td>{{ $row['qualified'] }}</td><td>{{ $row['leads'] ? round($row['qualified']/$row['leads']*100,1) : 0 }}%</td></tr>@empty<tr><td colspan="4">Belum ada UTM campaign.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Layanan diminati</h2></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Layanan</th><th>Lead</th><th>Potensi</th></tr></thead><tbody>@forelse($serviceRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['leads'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="3">Belum ada data.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Referral mitra</h2><span>Terpisah dari campaign</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Mitra</th><th>Lead</th><th>Selesai</th><th>Potensi</th></tr></thead><tbody>@forelse($partnerRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['leads'] }}</td><td>{{ $row['completed'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="4">Belum ada referral pada periode ini.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Pembuat tautan campaign</h2><span>Siap dibagikan</span></div><div class="p-4 stack-form"><label class="field"><span>Halaman layanan</span><select class="form-select" id="campaign-service">@foreach($services as $service)<option value="{{ route('services.show', $service->slug) }}">{{ $service->name }}</option>@endforeach<option value="{{ route('proposal.create') }}">Form proposal umum</option></select></label><div class="row g-2"><label class="field col-md-4"><span>Sumber</span><input class="form-control" id="campaign-source" value="whatsapp"></label><label class="field col-md-4"><span>Media</span><input class="form-control" id="campaign-medium" value="broadcast"></label><label class="field col-md-4"><span>Nama campaign</span><input class="form-control" id="campaign-name" placeholder="promo-agustus"></label></div><label class="field"><span>Tautan hasil</span><div class="input-group"><input class="form-control" id="campaign-url" readonly><button class="btn btn-outline-primary" type="button" id="copy-campaign-url">Salin</button></div></label><small class="text-muted">Gunakan nama campaign yang konsisten agar hasilnya terkumpul pada baris yang sama.</small></div></section></div>
</div>
@endsection

@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const ids=['campaign-service','campaign-source','campaign-medium','campaign-name'];const output=document.getElementById('campaign-url');const build=()=>{const base=document.getElementById('campaign-service').value;const url=new URL(base);url.searchParams.set('utm_source',document.getElementById('campaign-source').value.trim()||'whatsapp');url.searchParams.set('utm_medium',document.getElementById('campaign-medium').value.trim()||'broadcast');const name=document.getElementById('campaign-name').value.trim();if(name)url.searchParams.set('utm_campaign',name);output.value=url.toString()};ids.forEach(id=>document.getElementById(id).addEventListener('input',build));document.getElementById('copy-campaign-url').addEventListener('click',()=>navigator.clipboard.writeText(output.value));build()});</script>@endpush
