@extends('layouts.admin')

@section('title', 'Analitik Pertumbuhan')
@section('heading', 'Funnel & Pertumbuhan')
@section('header_action')<div class="d-flex gap-2">@if($campaignRoiEnabled)<a class="btn btn-outline-primary" href="{{ route('admin.marketing-campaigns.index') }}">Kelola campaign & biaya</a>@endif<div class="btn-group">@foreach([7,30,90] as $period)<a class="btn {{ $days === $period ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ route('admin.growth.index', ['days'=>$period]) }}">{{ $period }} hari</a>@endforeach</div></div>@endsection

@section('content')
<div class="admin-note mb-3">Ringkasan {{ $from->translatedFormat('d F Y') }}–{{ now()->translatedFormat('d F Y') }}. Deal tetap dilakukan manual melalui WhatsApp; dashboard menunjukkan lead mana yang perlu didahulukan.</div>

@if($recommendations->isNotEmpty())
<section class="conversion-recommendations mb-3"><div class="conversion-recommendations-head"><div><span>Prioritas hari ini</span><h2>Tindakan yang paling dekat dengan deal</h2></div><strong>{{ $recommendations->sum('count') }} item</strong></div><div class="conversion-recommendation-list">@foreach($recommendations as $item)<a href="{{ $item['url'] }}"><strong>{{ $item['count'] }}</strong><span>{{ $item['title'] }}</span><small>{{ $item['action'] }} →</small></a>@endforeach</div></section>
@endif

<section class="growth-metrics mb-3">
    <article><span>Lead masuk</span><strong>{{ number_format($metrics['leads']) }}</strong></article>
    <article><span>Penawaran terkirim</span><strong>{{ number_format($metrics['quotes']) }}</strong></article>
    <article><span>Disetujui</span><strong>{{ number_format($metrics['approved_quotes']) }}</strong><small>{{ $metrics['conversion'] }}% dari lead</small></article>
    <article><span>Nilai invoice</span><strong>Rp{{ number_format($metrics['invoiced'],0,',','.') }}</strong></article>
    <article><span>Pembayaran masuk</span><strong>Rp{{ number_format($metrics['collected'],0,',','.') }}</strong></article>
    <article><span>Rata-rata respons pertama</span><strong>{{ $metrics['response_minutes'] !== null ? number_format($metrics['response_minutes']).' menit' : 'Belum ada' }}</strong></article>
</section>

<div class="row g-3 mb-3">
    <div class="col-xl-7"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Funnel lead menjadi deal</h2><span>Berdasarkan lead yang masuk pada periode ini</span></div><div class="funnel-list p-4">@foreach($funnel as $step)<div><div><strong>{{ $step['label'] }}</strong><span>{{ $step['count'] }} · {{ $step['rate'] }}%</span></div><div class="funnel-track"><span style="width:{{ max(2,$step['rate']) }}%"></span></div></div>@endforeach</div></section></div>
    <div class="col-xl-5"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Alasan tidak lanjut</h2><span>Dasar memperbaiki penawaran</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Alasan</th><th>Lead</th><th>Potensi hilang</th></tr></thead><tbody>@forelse($lossRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['count'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="3">Belum ada lead gagal pada periode ini.</td></tr>@endforelse</tbody></table></div></section></div>
</div>

@if($campaignRoiEnabled)<section class="admin-panel mb-3"><div class="admin-panel-head"><h2>ROI campaign</h2><a href="{{ route('admin.marketing-campaigns.index') }}">Kelola landing & biaya</a></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Campaign</th><th>Kunjungan</th><th>Lead</th><th>Konversi form</th><th>Disetujui</th><th>Biaya/lead</th><th>Pembayaran</th><th>ROI</th></tr></thead><tbody>@forelse($campaignRows as $row)<tr><td><strong>{{ $row['name'] }}</strong><small>Biaya Rp{{ number_format($row['spend'],0,',','.') }}</small></td><td>{{ number_format($row['views']) }}</td><td>{{ $row['leads'] }}</td><td>{{ $row['landing_conversion'] === null ? '—' : number_format($row['landing_conversion'],1,',','.').'%' }}</td><td>{{ $row['approved'] }}</td><td>Rp{{ number_format($row['cost_per_lead'],0,',','.') }}</td><td>Rp{{ number_format($row['collected'],0,',','.') }}</td><td><strong class="{{ $row['roi'] !== null && $row['roi'] < 0 ? 'text-danger' : 'text-success' }}">{{ $row['roi'] === null ? 'Masukkan biaya' : number_format($row['roi'],1,',','.').'%' }}</strong></td></tr>@empty<tr><td colspan="8">Belum ada campaign terukur.</td></tr>@endforelse</tbody></table></div></section>@endif

<div class="row g-3">
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Sumber lead</h2><span>UTM/referral/website</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Sumber</th><th>Lead</th><th>Terkualifikasi</th><th>Potensi</th></tr></thead><tbody>@forelse($sourceRows as $row)<tr><td><strong>{{ $row['name'] }}</strong></td><td>{{ $row['leads'] }}</td><td>{{ $row['qualified'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="4">Belum ada data.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Layanan diminati</h2></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Layanan</th><th>Lead</th><th>Potensi</th></tr></thead><tbody>@forelse($serviceRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['leads'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="3">Belum ada data.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Referral mitra</h2><span>Terpisah dari campaign</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Mitra</th><th>Lead</th><th>Selesai</th><th>Potensi</th></tr></thead><tbody>@forelse($partnerRows as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['leads'] }}</td><td>{{ $row['completed'] }}</td><td>Rp{{ number_format($row['value'],0,',','.') }}</td></tr>@empty<tr><td colspan="4">Belum ada referral.</td></tr>@endforelse</tbody></table></div></section></div>
    <div class="col-xl-6"><section class="admin-panel h-100"><div class="admin-panel-head"><h2>Pembuat tautan cepat</h2>@if($campaignRoiEnabled)<a href="{{ route('admin.marketing-campaigns.index') }}">Simpan campaign</a>@endif</div><div class="p-4 stack-form"><label class="field"><span>Halaman layanan</span><select class="form-select" id="campaign-service">@foreach($services as $service)<option value="{{ route('services.show',$service->slug) }}">{{ $service->name }}</option>@endforeach<option value="{{ route('proposal.create') }}">Form proposal umum</option></select></label><div class="row g-2"><label class="field col-md-4"><span>Sumber</span><input class="form-control" id="campaign-source" value="whatsapp"></label><label class="field col-md-4"><span>Media</span><input class="form-control" id="campaign-medium" value="broadcast"></label><label class="field col-md-4"><span>Campaign</span><input class="form-control" id="campaign-name" placeholder="promo-agustus"></label></div><label class="field"><span>Tautan hasil</span><div class="input-group"><input class="form-control" id="campaign-url" readonly><button class="btn btn-outline-primary" type="button" id="copy-campaign-url">Salin</button></div></label></div></section></div>
</div>
@endsection

@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const ids=['campaign-service','campaign-source','campaign-medium','campaign-name'];const output=document.getElementById('campaign-url');const build=()=>{const url=new URL(document.getElementById('campaign-service').value);url.searchParams.set('utm_source',document.getElementById('campaign-source').value.trim()||'whatsapp');url.searchParams.set('utm_medium',document.getElementById('campaign-medium').value.trim()||'broadcast');const name=document.getElementById('campaign-name').value.trim();if(name)url.searchParams.set('utm_campaign',name);output.value=url.toString()};ids.forEach(id=>document.getElementById(id).addEventListener('input',build));document.getElementById('copy-campaign-url').addEventListener('click',()=>navigator.clipboard.writeText(output.value));build()});</script>@endpush
