@extends('layouts.admin')

@section('title', 'Template Penawaran')
@section('heading', 'Template Penawaran')

@section('content')
<div class="admin-note mb-3">Template mempercepat respons tanpa mengunci isi. Admin masih dapat mengubah ruang lingkup dan ketentuan pada setiap draf penawaran.</div>
<details class="admin-panel mb-3" @if($errors->any()) open @endif><summary class="admin-panel-head"><h2>Tambah template</h2><span>Untuk semua atau satu layanan</span></summary><form class="p-4 form-grid" method="post" action="{{ route('admin.quote-templates.store') }}">@csrf
    <label class="field"><span>Nama *</span><input class="form-control" name="name" value="{{ old('name') }}" required></label><label class="field"><span>Layanan</span><select class="form-select" name="service_id"><option value="">Semua layanan</option>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select></label>
    <label class="field field-wide"><span>Ruang lingkup</span><textarea class="form-control" name="scope" rows="6">{{ old('scope') }}</textarea></label><label class="field field-wide"><span>Ketentuan</span><textarea class="form-control" name="terms" rows="6">{{ old('terms') }}</textarea></label>
    <label class="field"><span>Masa berlaku (hari)</span><input class="form-control" type="number" min="1" max="90" name="validity_days" value="{{ old('validity_days',14) }}" required></label><label class="field"><span>Jatuh tempo invoice (hari)</span><input class="form-control" type="number" min="1" max="90" name="invoice_due_days" value="{{ old('invoice_due_days',7) }}" required></label>
    <label class="field field-wide"><span>Catatan</span><textarea class="form-control" name="notes" rows="2">{{ old('notes') }}</textarea></label><input type="hidden" name="is_active" value="1"><div><button class="btn btn-primary">Simpan template</button></div>
</form></details>

<div class="quote-template-grid">@foreach($templates as $template)<article class="admin-panel"><form class="p-3 stack-form" method="post" action="{{ route('admin.quote-templates.update', $template) }}">@csrf @method('PUT')
    <div class="d-flex justify-content-between"><span class="status status-{{ $template->is_active ? 'paid' : 'cancelled' }}">{{ $template->is_active ? 'Aktif' : 'Nonaktif' }}</span><small>Dipakai {{ $template->use_count }} kali</small></div><label class="field"><span>Nama</span><input class="form-control" name="name" value="{{ $template->name }}" required></label><label class="field"><span>Layanan</span><select class="form-select" name="service_id"><option value="">Semua layanan</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected($template->service_id === $service->id)>{{ $service->name }}</option>@endforeach</select></label>
    <label class="field"><span>Ruang lingkup</span><textarea class="form-control" name="scope" rows="6">{{ $template->scope }}</textarea></label><label class="field"><span>Ketentuan</span><textarea class="form-control" name="terms" rows="6">{{ $template->terms }}</textarea></label><div class="row g-2"><label class="field col-6"><span>Berlaku</span><input class="form-control" type="number" min="1" max="90" name="validity_days" value="{{ $template->validity_days }}"></label><label class="field col-6"><span>Jatuh tempo</span><input class="form-control" type="number" min="1" max="90" name="invoice_due_days" value="{{ $template->invoice_due_days }}"></label></div><label class="field"><span>Catatan</span><textarea class="form-control" name="notes" rows="2">{{ $template->notes }}</textarea></label><label class="check-field"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($template->is_active)> Aktif</label><button class="btn btn-primary">Simpan perubahan</button>
</form><form class="px-3 pb-3" method="post" action="{{ route('admin.quote-templates.destroy', $template) }}" onsubmit="return confirm('Hapus/nonaktifkan template ini?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus/nonaktifkan</button></form></article>@endforeach</div>
@endsection
